app/admin/routes.py
from flask import Blueprint, render_template, redirect, request, url_for, send_from_directory, abort, flash
from app.database import  User, db, Banned, Order, OrderModel, Model
from flask_login import current_user

admin = Blueprint('admin', __name__)

@admin.route('/admin', methods=['GET', 'POST'])
def admin_index():
    if current_user.is_authenticated:
        if current_user.id == 1:
            return render_template('adminpage.html')
    abort(404)

@admin.route('/admin/transakcije')
def admin_transakcije():
    if current_user.id == 1:
        transakcije = Order.query.all() #provizorno!
        for elem in transakcije:
            if elem.user_id == 0:
                elem.username = "Neregistrirani korisnik"
            else:
                elem.username = User.query.filter_by(id=elem.user_id).first().username
        return render_template('transakcije.html', title='Lista transakcija',  transakcije=transakcije) #potrebna je html tablica
    else:
        abort(404)

@admin.route('/transakcija/<int:transaction_id>')
def transakcije_pojedinacno(transaction_id):
    if current_user.id == 1:
        order = Order.query.filter_by(id=transaction_id).first()
        models = OrderModel.query.filter_by(order_id=transaction_id).all()
        price = 0
        for elem in models:
            elem.model_name = Model.query.filter_by(id=elem.model_id).first().name
            price += elem.price * elem.quantity
        return render_template('transakcije_pojedinacno.html', title='Transakcija ' + str(transaction_id), models=models, order=order, price=price)
    else:
        abort(404)

@admin.route('/admin/userlist')
def admin_userlist():
    if current_user.is_authenticated:
        if current_user.id == 1:
            users = User.query.all()
            return render_template('lista_korisnika.html', title='Lista korisnika', users=users)
    abort(404)

@admin.route('/admin/ban/<int:user_id>')
def admin_ban(user_id):
    print(user_id)
    if user_id == 1:
        flash("Adminu ne može biti zabranjen pristup")
    else:
        banuser = User.query.filter_by(id=user_id).first()
        banneduser = Banned(email=banuser.email)
        db.session.delete(banuser)
        db.session.commit()
        db.session.add(banneduser)
        db.session.commit()
    return redirect(url_for('admin.admin_userlist'))

app/cart/routes.py
from flask import Blueprint, render_template, session
from sqlalchemy import exc
from app.database import db, Model, Cart, CartModel
from flask_login import login_user, current_user, logout_user

cart = Blueprint('cart', __name__)

@cart.route('/cart', methods=['GET', 'POST'])
#@login_required
def cart_Instance():
    models = []
    if current_user.is_authenticated:
        cart_inst = Cart.query.filter_by(buyer_id=current_user.id).first()
        if cart_inst is None:
            cart_inst = Cart(buyer_id=current_user.id)
            db.session.add(cart_inst)
            try:
                db.session.commit()
            except exc.SQLAlchemyError:
                pass
        contents = CartModel.query.filter_by(cart_id=cart_inst.buyer_id).all()
        for content in contents:
            model_elem = Model.query.filter_by(id=content.model_id).first()
            models.append(model_elem)
    else:
        if session.get('cart', None) is None:
            session['cart'] = []
        contents = session['cart']
        for elem in contents:
            model_elem = Model.query.filter_by(id=elem['model_id']).first()
            models.append(model_elem)
    return render_template('cart.html', title='Košarica', contents=contents, models=models, number=len(contents))

app/checkout/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_login import current_user
from app.checkout.forms import CheckoutForm
from app.database import PodaciPlacanje, db, Cart, CartModel, Order, OrderModel

checkout = Blueprint('checkout', __name__)

@checkout.route('/checkout', methods=['GET','POST'])
def checkout_page():
    form = CheckoutForm()
    if form.validate_on_submit():
        if current_user.is_authenticated and form.remember:
            billing_info = PodaciPlacanje.query.filter_by(user_id=current_user.id).first()
            billing_info.full_name = form.fname.data
            billing_info.email = form.email.data
            billing_info.address = form.adr.data
            billing_info.city = form.city.data
            billing_info.card_full_name = form.cname.data
            billing_info.card_number = form.ccnum.data
            billing_info.card_expiry = form.expdate.data
            billing_info.country = form.state.data
            billing_info.zip_code = form.zip.data
            billing_info.card_CVC = form.cvv.data
            db.session.commit()
        flush_cart(form)
        flash ('Uspješno obavljena kupnja', 'success')
        return redirect(url_for('index.homepage'))
    elif request.method == 'GET':
        if current_user.is_authenticated:
            billing_info = PodaciPlacanje.query.filter_by(user_id=current_user.id).first()
            form.fname.data = billing_info.full_name
            form.email.data = billing_info.email
            form.adr.data = billing_info.address
            form.city.data = billing_info.city
            form.cname.data = billing_info.card_full_name
            form.ccnum.data = billing_info.card_number
            form.expdate.data = billing_info.card_expiry
            form.state.data = billing_info.country
            form.zip.data = billing_info.zip_code
            form.cvv.data = billing_info.card_CVC
    return render_template('checkout.html',title = "Podaci za placanje", form = form)

def flush_cart(form):
    buyer_name = form.fname.data
    buyer_email = form.email.data
    buyer_address = form.adr.data + ', ' + form.zip.data + ' ' + form.city.data + ', ' + form.state.data
    if current_user.is_authenticated:
        cart = Cart.query.filter_by(buyer_id=current_user.id).first()
        order = Order(user_id=current_user.id, buyer_name=buyer_name, buyer_email=buyer_email, buyer_address=buyer_address)
        cart_contents = CartModel.query.filter_by(cart_id=cart.buyer_id).all()
        print(cart)
        db.session.delete(cart)
    else:
        cart_contents = list(session['cart'])
        order = Order(user_id=0, buyer_name=buyer_name, buyer_email=buyer_email, buyer_address=buyer_address)
        del session['cart']

    db.session.add(order)
    db.session.commit()

    if current_user.is_authenticated:
        for elem in cart_contents:
            order_elem = OrderModel(order_id=order.id, model_id=elem.model_id, material=elem.material, price=elem.price, quantity=elem.quantity)
            db.session.add(order_elem)
            db.session.delete(elem)
    else:
        for elem in cart_contents:
            order_elem = OrderModel(order_id=order.id, model_id=elem.get('model_id'), material=elem.get('material'),
                            price=elem.get('price'), quantity=elem.get('quantity'))
            db.session.add(order_elem)
            db.session.delete(elem)
    db.session.commit()
    return

app/index/routes.py
from app import application
from flask import Blueprint, render_template, redirect, request, url_for, send_from_directory, Flask

index = Blueprint('index', __name__)

@index.route('/')
def homepage():
    return render_template("index.html", title="Home")

app/profile/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from app.profile.forms import UpdateForm
from app.database import db, Profile, User

profile = Blueprint('profile', __name__)

#@profile.route('/Profil')
#def Profil():
#    user_profile = Profile.query.filter_by(id=current_user.id).first()
#    user_profile.Private_Ime = False
#    user_profile.Private_Prezime = False
#    user_profile.Private_Datum = False
#    user_profile.Private_Zivotopis = False
#    print(user_profile)
#    return render_template ('korracun_prikaz.html', title = 'Korisnički podaci', profile=user_profile)

@profile.route('/profil/<id>')
def User_Profil(id):
    user_profile = Profile.query.filter_by(id=id).first()
    user = User.query.filter_by(id=id).first()
    print(user.id)
    return render_template ('tudi_korracun_prikaz.html', title = 'Korisnički podaci', profile=user_profile, user=user)


@profile.route('/urediprofil', methods=['GET','POST'])
def Change():
    form = UpdateForm()
    user_profile = Profile.query.filter_by(id=current_user.id).first()
    if form.validate_on_submit():
        user_profile.Ime = form.Ime.data
        user_profile.Private_ime = form.Private_Ime.data
        user_profile.Prezime = form.Prezime.data
        user_profile.Private_prezime = form.Private_Prezime.data
        user_profile.Datum_rodenja = form.Datum_rodenja.data
        user_profile.Private_Datum = form.Private_Datum.data
        user_profile.Zivotopis = form.Zivotopis.data
        user_profile.Private_Zivotopis = form.Private_Zivotopis.data
        flash ('Promijenili ste podatke korisničkog računa', 'success')
        db.session.commit()
        return redirect(url_for('profile.User_Profil', id=current_user.id))
    elif request.method == 'GET':
        form.Ime.data = user_profile.Ime
        form.Private_Ime.data = user_profile.Private_ime
        form.Prezime.data = user_profile.Prezime
        form.Private_Prezime.data = user_profile.Private_prezime
        form.Datum_rodenja.data = user_profile.Datum_rodenja
        form.Private_Datum.data = user_profile.Private_Datum
        form.Zivotopis.data = user_profile.Zivotopis
        form.Private_Zivotopis.data = user_profile.Private_Zivotopis
    else:
        print(form.errors)
    return render_template('korracun_izmjena.html',title = "Izmjeni korisničke podatke", form = form)

app/store/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, session, send_from_directory
from sqlalchemy import exc
from app.database import User, db, Model, ModelPhoto, ModelPrice, Cart, CartModel, ModelNotification
from app.store.forms import ModelForm
from app import application
from flask_login import current_user
from uuid import uuid4
from os import path, listdir

store = Blueprint('store', __name__)

@store.route('/order_custom', methods=['GET', 'POST']) #potrebno dodati stranicu za admina
#@login_required
def new_model():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    form = ModelForm()
    if form.validate_on_submit():
        print("success")
        dimension = f"{form.dimension_1.data},{form.dimension_2.data},{form.dimension_3.data}"   #unesene dimenzije su spojene ',' npr. '100,120,150'
        colors = form.colors.data                                                                #unesene boje odvojene zarezom npr. 'plava,crvena,zelena'
        model = Model(name=form.name.data, description=form.description.data, creator_id=current_user.id, dimension=dimension, colors=colors) #dodati image_name
        db.session.add(model)
        db.session.commit()
        #dodati za photo i video obradu podataka    # file upload image/video
        filename = form.image.data.filename.split('.')
        extension = filename[-1]
        while True:
            filename = uuid4().hex + '.' + extension
            if filename not in listdir(path.join(application.root_path, application.config['MODEL_LOCATION'])):
                break

        form.image.data.save(path.join(application.root_path, application.config['MODEL_LOCATION'], filename))
        model_photo = ModelPhoto(image_name=filename, model_id=model.id)
        db.session.add(model_photo)
        db.session.commit()
        #flash('Nova maketa dodana!', 'succes')
        return redirect(url_for('index.homepage'))
    else:
        print(form.errors)
        for error in form.errors:
            print(error)
    return render_template('narudzba.html', title='Nova maketa', form=form)



@store.route('/makete_prikaz', methods=['GET', 'POST'])
#@login_required
def makete_prikaz_Instance():
    models = Model.query.filter_by(approved=True)
    return render_template('makete_prikaz.html', title='Makete', models=models)

@store.route('/makete/<int:model_id>', methods=['GET', 'POST'])
def model_Instance(model_id):
    model = Model.query.get_or_404(model_id)
    model_photo = ModelPhoto.query.filter_by(model_id=model.id).first().image_name
    model_dimensions = model.dimension.split(',')
    model_colors = model.colors.split(',')
    materials = ModelPrice.query.filter_by(model_id=model.id).all()
    model_creator = User.query.filter_by(id=model.creator_id).first()
    if request.method == "POST":
        if current_user.is_authenticated:
            cart_user = Cart.query.filter_by(buyer_id=current_user.id).first()
            if cart_user is None:
                cart_user = Cart(buyer_id=current_user.id)
                db.session.add(cart_user)
                try:
                    db.session.commit()
                except exc.SQLAlchemyError:
                    pass
            material_choice = request.form.get("materijaliChoose")
            item_in_cart = CartModel.query.filter_by(cart_id=cart_user.buyer_id, model_id=model.id, material=material_choice).first()
            if item_in_cart is None:
                item_price = ModelPrice.query.filter_by(model_id=model.id, material=material_choice).first().price
                cart_m_user = CartModel(cart_id=cart_user.buyer_id, model_id=model.id, material=material_choice, price=item_price, quantity=1)
                db.session.add(cart_m_user)
            else:
                item_in_cart.quantity += 1
            try:
                db.session.commit()
                #flash('Maketa dodana u košaricu!', 'succes')
            except exc.SQLAlchemyError:
                pass
        else:
            if not session.get('cart', None):
                session['cart'] = []
            material_choice = request.form.get("materijaliChoose")
            inCart = False
            for elem in session['cart']:
                if elem['model_id'] == model_id and elem['material'] == material_choice:
                    elem['quantity'] += 1
                    inCart = True
                    break
            if not inCart:
                item_price = ModelPrice.query.filter_by(model_id=model_id, material=material_choice).first().price
                session['cart'].append(dict(model_id=model_id, material=material_choice, price=item_price, quantity=1))
    return render_template('makete.html', title=model.name, model=model, model_photo=model_photo, materials=materials, dimensions=model_dimensions, colors=model_colors, model_creator=model_creator)

@store.route('/prihvatimaketu', methods=['GET', 'POST'])
def model_approval():
    if request.method == 'POST':
        print(request.form)
        model_id = request.form['order_id']
        model = Model.query.filter_by(id=model_id).first()
        if request.form['response'] == 'Odbij':
            db.session.delete(model)
        else:
            model.approved = True
            for mat in application.config['MATERIALS']:
                MP = ModelPrice(model_id=model_id, material=mat, price=request.form[mat])
                db.session.add(MP)
            notif = ModelNotification(model_id=model_id, receiver_id=model.creator_id)
            db.session.add(notif)
        try:
            db.session.commit()
        except exc.SQLAlchemyError:
            pass
        return redirect(url_for('store.model_approval'))
    orders = Model.query.filter_by(approved=False)
    return render_template('prihvat_makete.html', orders=orders, materials=application.config['MATERIALS'])

@store.route('/obavijesti')
def my_notifications():
    if current_user.is_authenticated:
        notifs = ModelNotification.query.filter_by(receiver_id=current_user.id).order_by(ModelNotification.time_create.desc()).all()
        models = []
        for notif in notifs:
            models.append(Model.query.filter_by(id=notif.model_id).first())
            notif.seen = True
        db.session.commit()
    else:
        return redirect(url_for("auth.login"))
    return render_template('makete_prikaz.html', title='Obavijesti', models=models)

@store.route('/model_photo/<file>')
def pull_file(file):
    route = path.join(application.root_path, application.config['MODEL_LOCATION'])
    print(route)
    return send_from_directory(route, file)

app/templates/adminpage.html
{% extends "layout.html" %}
{% set active_page = "makete" %}

{% block content %}

<section id="main">
    <h1 class="admin-title">Admin - Kontrolna ploča</h1>
    <div class="sec-main-container">
        <div class="admin-link-hold">
            <a href="{{url_for('admin.admin_userlist')}}" class="admin-link">
                <div title="Otvorite userlist" id="userlistLink" class="admin-link">USERLIST</div>
            </a>
        </div>

        <div class="admin-link-hold">
            <a href="{{url_for('story.display_story_list_validation')}}" class="admin-link">
                <div title="Otvorite userlist" id="userlistLink" class="admin-link">Prihvat priča</div>
            </a>
        </div>

        <div class="admin-link-hold">
            <a href="{{url_for('store.model_approval')}}" class="admin-link">
                <div title="Otvorite userlist" id="userlistLink" class="admin-link">Prihvat maketa</div>
            </a>
        </div>

        <div class="admin-link-hold">
            <a href="{{url_for('admin.admin_transakcije')}}" class="admin-link">
                <div title="Povijest transakcija" id="userlistLink" class="admin-link">Povijest transkacija</div>
            </a>
        </div>
    </div>
</section>

{% endblock %}

app/templates/index.html
{% extends "layout.html" %}
{% set active_page = "pocetna" %}

{% block content %}

<section id="showcase">
	<div class="container">
		<h1>Dobro došli</h1>
		<p>Mjesto gdje vaše ideje pretvaramo u stvarnost.</p>
	</div>
</section>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>

<html>

	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<!-- Dodati glavni naslov svakoj stranici -->
		<link rel="stylesheet" href="../static/styles/style.css">
		<script src="../static/js/main.js"></script>
    {% if title %}
        <title>MaketaShop-{{ title }}</title>
    {% else %}
        <title>MaketaShop</title>
    {% endif %}
	</head>

	{% if current_user.is_authenticated %}
		{% set notifications = current_user.getNotifications() %}
	{% endif %}

	<body>

		<header>
			<div class="container">
				<div id="branding">
					<h1><span class="highlight">Maketa</span> Shop</h1>
				</div>

				<nav>
					<ul>
						<!-- Svaka stranica postavlja varijablue active_page koja označava trenutni izbornik -->
						<li {% if active_page == "pocetna" %} class="current" {% endif %}><a href="{{ url_for('index.homepage')}}">Početna</a></li>
						<li {% if active_page == "price" %} class="current" {% endif %}>
							<div class="dropdown">
								<button class="dropbtn"><a href="{{ url_for('story.display_story_list') }}">Priče</a></button>
								<div class="dropdown-content">
									<a id="decolour-nav" href="{{ url_for('story.add_content') }}">Predloži</a>
								</div>
							</div>
						</li>
						<li {% if active_page == "makete" %} class="current" {% endif %}>
							<div class="dropdown">
								<button class="dropbtn"><a href="{{ url_for('store.makete_prikaz_Instance') }}">Makete
								{% if notifications %}
									<img src="../static/img/exclamation-16.ico">
								{% endif %}</a></button>
								<div class="dropdown-content">
									<a id="decolour-nav" href="{{ url_for('store.new_model') }}">Naruči</a>
                                    <a id="decolour-nav" href="{{ url_for('store.my_notifications') }}">Obavijesti</a>
								</div>
							</div>
						</li>
						<li {% if active_page == "cart" %} class="current" {% endif %}><a href="{{ url_for('cart.cart_Instance')}}"><img src="../static/img/shopping_cart.png" width="25px" height="25px"></a></li>
						{% if not current_user.is_authenticated %}
						<li {% if active_page == "prijava" %} class="current" {% endif %}><a href="{{ url_for('auth.login') }}">Prijavi se</a><li>
						<li {% if active_page == "registracija" %} class="current" {% endif %}><a href="{{ url_for('auth.register') }}">Registriraj se</a> </li>
						{% else %}
                        <li {% if active_page == "profile" %} class="current" {% endif %}>
							<div class="dropdown">
								<button class="dropbtn"><a href="{{ url_for('profile.User_Profil', id=current_user.id) }}">Moj profil</a></button>
								<div class="dropdown-content">
									<a id="decolour-nav" href="{{ url_for('profile.Change') }}">Uredi</a>
									{% if current_user.id == 1 %}
									<a id="decolour-nav" href="{{ url_for('admin.admin_index') }}">Admin</a>
									{% endif %}
								</div>
							</div>
						</li>
						<li><a href="{{ url_for('auth.logout') }}">Odjavi se</a> </li>
						{% endif %}
					</ul>
				</nav>
			</div>
		</header>

		{% block content %}
		...ubaciti sadržaj...
		{% endblock %}

		<footer></footer>

	</body>

</html>

app/templates/lista_korisnika.html
{% extends "layout.html" %}
{% set active_page = "makete" %}

{% block content %}

<div class="main-container">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="table-holder table-spacer">
        <table class="w3-table-all w3-centered">
            <thead>
                <tr class="w3-orange">
                    <th>Username</th>
                    <th>Email</th>
                    <th>LINK</th>
                    <th>BAN</th>
                </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td><a href="{{url_for('profile.User_Profil', id=user.id)}}" id="userLink" title="Otvorite stranicu usera">User page</a></td>
                    <td><a href="{{url_for('admin.admin_ban', user_id=user.id)}}" id="userBan" title="User ban">BAN user</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/makete.html
{% extends "layout.html" %}
{% set active_page = "makete" %}

{% block content %}

<!--

<script src="../static/js/cycler.js"></script>
<script src="../static/js/main.js"></script>

<span hidden id="elem-count">2</span>
<span hidden class="img-cycle" id="elem-cycle-0">../static/img/pocetna.png</span>
<span hidden class="vid-cycle" id="elem-cycle-1">../static/vid/video.mp4</span>

-->

<div class="regErrMsg"></div>

<section id="main">
    <div class="container main-container">
        <article id="main-col">
            <h1 class="page-title"></h1>
            <ul id="services">
                <li>
                    <p id="naslovPrice"> {{ model.name }} </p>
                    <div class="flex-container">
                        <div class="flex-container-column">
                            <div class="flex-element flex-element-tekst">
                                <b class="tekstHeader">Opis makete</b><br/>
                                {{ model.description }}
                            </div>
                            <div class="flex-element flex-element-tekst flex-element-specifikacije">
                                <b class="tekstHeader">Specifikacije</b><br/>
                                    <span class="specSpan">Cijena:  </span>
                                    <span id="prices">
                                        <span class="emph" value="">Odaberite materijal</span>
                                    {% for material in materials %}
                                        <span value="{{ material.material }}" hidden>{{ material.price }}</span>
                                    {% endfor %}
                                    </span>
                                    <br/>
                                    <span class="specSpan">Boje: {% for color in colors %}
                                    {{ color }} 
                                    {% endfor %}</span>
                                    <br/>
                                    <span class="specSpan">Dimenzije: {% for dimension in dimensions %} 
                                    {{ dimension }}cm 
                                    {% endfor %}</span>
                                    <br/>
                            </div>
                            <div class="flex-element flex-element-tekst flex-element-specifikacije">
                                <b class="tekstHeader">Autor</b><br/>
                                    <span class="specSpan"><a id="priceLink" href="{{ url_for('profile.User_Profil', id=model_creator.id) }}">{{ model_creator.username }}</a></span>
                            </div>
                            <form id="addToCart" method="POST" class="cart-func form-deselect">
                                <div class="elem-chooser flex-element-tekst">
                                    <label class="label-ponistavanje" for="materijalChoose"><b class="tekstHeader">Odaberite materijal</b></label><br/>
                                    <select id="materijaliChoose" name="materijaliChoose" size="1" onchange="updatePrice()" required>
                                        <option disabled selected value>--odaberite--</option>
                                            {% for material in materials %}
                                                <option value="{{ material.material }}">{{ material.material }}</option>
                                            {% endfor %}
                                    </select>
                                </div>
                                <input type="submit" class="main-button subBtn add-to-cart" value="Dodaj u kosaricu"><br/>
                            </form>
                        </div>
                        <div class="flex-container-column flex-video-img">
                            <!--<video class="flex-element" controls>
                                <source src="{ url_for('static', filename='vid/' + model_video) }" type="video/mp4">
                            </video>-->
                            <img class="flex-element" id="maketaSlika"
                                src="{{ url_for('store.pull_file', file=model_photo) }}">
                        </div>
                    </div>
                </li>
            </ul>
        </article>
    </div>
</section>
<script>
    updatePrice()
</script>

{% endblock %}

app/templates/price.html
{% extends "layout.html" %}
{% set active_page = "price" %}

{% block content %}

<div class="regErrMsg"></div>

<section id="main">
	<div class="container">
		<article id="main-col">
			<h1 class="page-title"></h1>
			<ul id="services">
				{% for story in stories %}
				<a href="{{url_for('story.display_story', story_id=story.id)}}"  id="priceLink" title="Otvorite citavu pricu">
					<li>
						<h3>{{ story.title }}</h3>
						<p>{{ story.author_name }}</p>
					</li>
				</a>
				{% endfor %}
			</ul>
		</article>
	</div>
</section>
	
{% endblock %}

app/templates/transakcije_pojedinacno.html
{% extends "layout.html" %}
{% set active_page = "profile" %}

{% block content %}

<div class="main-container">
    <div class="table-holder table-spacer">
        <div class="container">
            <article>
                <h1 class="page-title"></h1>
                <ul id="services">
                    <li>
                        <h3>ID: {{ order.id }}</h3>
                        <p>Vrijeme: {{ order.time_created }}</p>
                        <p>Ime kupca: {{ order.buyer_name }}</p>
                        <p>Email kupca: {{ order.buyer_email }}</p>
                        <p>Adresa: {{ order.buyer_email }}</p>
                        <p>Ukupna cijena: {{ price }}kn</p>
                    </li>
                </ul>
            </article>
        </div>
        <table class="w3-table-all w3-centered">
            <thead>
                <tr class="w3-orange">
                    <th>Maketa</th>
                    <th>Materijal</th>
                    <th>Količina</th>
                    <th>Cijena</th>
                </tr>
            </thead>
            <tbody>
            {% for elem in models %}
                <tr>
                    <td><a href="{{ url_for('store.model_Instance', model_id=elem.model_id) }}"> {{ elem.model_name }} </a></td>
                    <td>{{ elem.material }}</td>
                    <td>{{ elem.quantity }}</td>
                    <td>{{ elem.quantity * elem.price }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/tudi_korracun_prikaz.html
{% extends "layout.html" %}
{% set active_page = "profile" %}

{% block content %}

<section id="main">
    <div class="main-container container">
        <div class="cont-style" method="POST">
            <h1 class="kor-page-title">{{ user.username }}</h1>

            <div class="kor-pregled">
                {% if profile.Private_ime %}
                    <div class="pre-elem"><span class="kor-pre-desc">Ime: </span>privatno</div>
                {% else %}
                    <div class="pre-elem"><span class="kor-pre-desc">Ime: </span>{{ profile.Ime }}</div>
                {% endif %}
                {% if profile.Private_prezime %}
                    <div class="pre-elem"><span class="kor-pre-desc">Prezime: </span>privatno</div>
                {% else %}
                    <div class="pre-elem"><span class="kor-pre-desc">Prezime: </span>{{ profile.Prezime }}</div>
                {% endif %}
                {% if profile.Private_Datum %}
                    <div class="pre-elem"><span class="kor-pre-desc">Datum rođenja: </span>privatno</div>
                {% else %}
                    <div class="pre-elem"><span class="kor-pre-desc">Datum rođenja: </span>
                        {% if profile.Datum_rodenja %}
                            {{ profile.Datum_rodenja.strftime('%d.%m.%Y.') }}
                        {% endif %}
                    </div>
                {% endif %}
                <div class="flex-pre pre-elem">
                    <div class="kor-pre-desc">
                        Životopis:
                    </div>
                    {% if profile.Private_Zivotopis %}
                        <div class="kor-pre-info">privatno</div>
                    {% else %}
                        <div class="kor-pre-info">{{ profile.Zivotopis }}</div>
                    {% endif %}
                </div>
            </div>
            {% if user.id == current_user.id %}
                <div class="btnHolder">
                    <a class="kor-btn ctrl-prijedlog" href="{{ url_for('profile.Change') }}">Uredi profil</a>
                </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}